[package]
name = "backend"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
axum = "0.8.9"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7.0", features = ["fs"] }
mime = "0.3"
crossbeam = "0.8"
chrono = { version = "0.4", features = ["clock"] }
wide = "1.5"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
strip = "symbols"
panic = "abort"
