#!/usr/bin/env bash
set -euo pipefail

# ── FALCON WASM Build Pipeline ───────────────────────────────────
# Produces:
#   pkg/falcon_wasm_bg.wasm    — optimized WASM binary
#   pkg/falcon_wasm.js          — JS glue (wasm-bindgen)
#   pkg/falcon_wasm.d.ts        — TypeScript declarations
#   pkg/falcon_wasm_inline.js   — inline JS: Uint8Array + init()
#                                 for embedding in HTML/MHTML

CRATE_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_DIR="$CRATE_DIR/pkg"

mkdir -p "$PKG_DIR"

echo "→ Building for wasm32-unknown-unknown (release)..."
rtk cargo build --target wasm32-unknown-unknown --release \
    --manifest-path "$CRATE_DIR/Cargo.toml"

WASM_SRC="$CRATE_DIR/target/wasm32-unknown-unknown/release/falcon_wasm.wasm"

echo "→ Running wasm-bindgen..."
wasm-bindgen "$WASM_SRC" --out-dir "$PKG_DIR" --target web

echo "→ Running wasm-opt (dead code stripping + size optim)..."
wasm-opt -Oz \
    --enable-bulk-memory \
    --enable-nontrapping-float-to-int \
    -o "$PKG_DIR/falcon_wasm_bg.wasm" \
    "$PKG_DIR/falcon_wasm_bg.wasm"

WASM_OPTIMIZED="$PKG_DIR/falcon_wasm_bg.wasm"
WASM_SIZE=$(stat -f%z "$WASM_OPTIMIZED" 2>/dev/null || stat -c%s "$WASM_OPTIMIZED" 2>/dev/null)
echo "  WASM size: $WASM_SIZE bytes ($(( WASM_SIZE / 1024 ))KB)"

echo "→ Generating inline JS (falcon_wasm_inline.js)..."
# Convert wasm to a JS Uint8Array literal
WASM_HEX=$(xxd -p < "$WASM_OPTIMIZED" | tr -d '\n')
BYTES=""
for (( i=0; i<${#WASM_HEX}; i+=2 )); do
    BYTES="${BYTES}0x${WASM_HEX:$i:2},"
done
BYTES="${BYTES%,}"

cat > "$PKG_DIR/falcon_wasm_inline.js" << EOF
// ── FALCON WASM (inline) — generated by build.sh ──
// Optimized WASM size: $WASM_SIZE bytes
// Embed this in HTML/MHTML to avoid external fetch.

const falconWasmBytes = new Uint8Array([$BYTES]);

let falconInstance = null;

export async function falconInit() {
    if (falconInstance) return falconInstance;
    const { instance } = await WebAssembly.instantiate(falconWasmBytes, {
        wbg: { __wbindgen_throw: (ptr, len) => { throw new Error("wasm panic"); } },
    });
    falconInstance = instance;
    return instance;
}

export async function falconGenerateKeypair(logn) {
    const instance = await falconInit();
    // Call the exported wasm-bindgen wrapper
    const exports = instance.exports;
    // ... (wasm-bindgen generated)
}
EOF

echo "  Inline JS: $PKG_DIR/falcon_wasm_inline.js"
echo ""
echo "✓ Done. Files in $PKG_DIR:"
ls -lh "$PKG_DIR" | grep -v '\.tmp$'
