FROM dhi.io/nginx:1-alpine

COPY nginx/default.conf                     /etc/nginx/conf.d/default.conf
COPY nginx/certs/selfsigned.crt             /etc/nginx/certs/selfsigned.crt
COPY --chmod=644 nginx/certs/selfsigned.key /etc/nginx/certs/selfsigned.key
COPY static/                                /static/
