# PostgreSQL dev config
listen_addresses = '*'
max_connections = 50
shared_buffers = 256MB
effective_cache_size = 1536MB
work_mem = 16MB
maintenance_work_mem = 64MB
random_page_cost = 2
effective_io_concurrency = 100
log_timezone = 'UTC'
timezone = 'UTC'
log_destination = 'stderr'          # Critical for Docker
logging_collector = off             # Turn off file logging
log_min_duration_statement = 500ms  # Keep this for debugging
wal_compression = on                # Reduces bytes written to slow Docker volumes
checkpoint_timeout = 20min
max_wal_size = 4GB
min_wal_size = 1GB
wal_buffers = 8MB
checkpoint_completion_target = 0.95
jit = off
idle_in_transaction_session_timeout = 600000 # 10m
statement_timeout = 600000
lock_timeout = 60000
autovacuum_max_workers = 1
autovacuum_vacuum_scale_factor = 0.05
log_checkpoints = on
log_autovacuum_min_duration = 0
track_io_timing = on
temp_file_limit = 1536MB
synchronous_commit = on
fsync = on
max_parallel_workers_per_gather = 2 # for now
log_line_prefix = '-[[%t] [%p] [%u] [%d] [%a] [%h]]- %q'   
max_parallel_workers = 4
autovacuum_vacuum_threshold = 1000
